spring:
  application:
    name: sb_webapp
  profiles:
    # 운영환경(prod), 개발환경(dev), 로컬환경(local)을 분리한다.
    active: local
    #    include: test
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080